version: '3.2'
networks:
  shared-network:
    driver: bridge
services:
  btc_wallet:
    networks:
      - shared-network
    hostname: "host"
    ipc: host
    pid: "host"
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "8010:8010"
    restart: always

  db:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=mywallet
      - APP_DB_PASS=mywallet
      - APP_DB_NAME=my_wallet
    volumes:
      - ./docker/script/0-init.sh:/docker-entrypoint-initdb.d/0-init.sh
    ports:
      - 5003:5432
  # prest:
  #   networks:
  #     - shared-network
  #   image: prest/prest
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #      - docker/env/prest.env
  #   depends_on:
  #     - db